---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bouda
  labels:
    app: bouda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bouda
  template:
    metadata:
      labels:
        app: bouda
    spec:
      containers:
      - name: bouda
        image: hachemi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
